spring:
  application:
    name: sell_buy
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g66b19f3607d868_maindb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: gbin1
    password: Globalinorcl1
    driver-class-name: oracle.jdbc.OracleDriver
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    show-sql: false
  cloud:
    aws:
      credentials:
        access-key: AKIA6K5V7S2RLV5WUQOS
        secret-key: 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
      region:
        static: ap-northeast-1
server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      cookie:
        name: JSESSIONID
      timeout: 60m
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
