spring:
  application:
    name: sell_buy
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g66b19f3607d868_maindb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: admin
    password: Globalinorcl1
    driver-class-name: oracle.jdbc.OracleDriver
