name: CD
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 코드 가져오기
        uses: actions/checkout@v3

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Amazon ECR 로그인
        uses: aws-actions/amazon-ecr-login@v1

      - name: JDK 17 설치
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: gradlew 실행 권한 주기
        run: chmod +x ./gradlew

      - name: Jib으로 빌드하고 ECR에 이미지 푸시
        run: ./gradlew clean jib -x test

      - name: Task Definition 파일 업데이트
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1  
        with:
          task-definition: task-definition.json 
          container-name: globalin 
          image: ${{ steps.jib.outputs.image }} 

      - name: AWS ECS 배포
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }} 
          cluster: Globalin 
          service: Globalin 
          wait-for-service-stability: true 
